predict:
  modelPath: "/hadoop/model" #模型文件路径
  outputPath: "/hadoop/output" #预测结果输出路径


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      force-request: true
      force-response: true
